version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_shop
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shop-network

  redis:
    image: redis:latest
    container_name: redis_shop
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
