spring:
  application:
    name: redis-mongo-example

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cache:
  ttl: ${CACHE_TTL}
server:
  port: ${SERVER_PORT}
